# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-15 04:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cmdb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disk',
            name='iface_type',
            field=models.CharField(choices=[('SATA', 'SATA'), ('SAS', 'SAS'), ('SCSI', 'SCSI'), ('SSD', 'SSD')], max_length=64, verbose_name='接口类型'),
        ),
    ]
